### PR TITLE
Changes to include stuff from the expansion

### LINKED ISSUE #9: Expansion Content Update
@ohgoditspotato , Might I suggest adding the new treachery cards and factions from the expansion? Perhaps have a toggle that allows you to optionally add the new cards? Thanks! Keep up the great work.

### PR DESCRIPTION
**Pull request by Ortimer**
I did my best to include the new 2 houses and the new treachery cards from the expansion.
I wasn't able to get vector art for the new houses so they are using colored emperor art at the moment.
I'm a backend developer so don't judge the ugliness of my code too much.

### CODE REVIEW

**Comment by ohgoditspotato** [comment]
Hi Esteban,
Thanks for the pull request - looks great! I've not had the time to look at this project lately (and also I've not been able to play dune with anyone due to Covid...) - but this PR looks fab - I'll merge it now and it should go live on github pages shortly after.

I liked the improvement to the card counting - sometimes it's a lot prettier just to do a swift cast to "any" and then write something elegant, rather than beating your head against the type system like I did...

Thanks again,
Rob

**Comment by Ortimer** [comment]
Rob don't forget to change the vector art for Ixians and Tleilaxu that I wasn't able to find or make something good for them, so I just put something temporal (Emperor icon with different color)

**Comment by ohgoditspotato** [comment]
Ah yes - I've not got any for them either, I nabbed the original stuff of a kind upload on board game geek - maybe it's been updated with the expansion houses, I'll check.

**Comment by ohgoditspotato** [comment]
Fixes #9 

Added the images for the expo houses.

**Pull request merged**
